image: alpine:latest

stages:
  - test

test27:
  stage: test
  image: python:2.7
  script:
    - pip install -r requirements_test.txt
    - pytest --cov trivago -- tests
  tags:
    - docker

test34:
  stage: test
  image: python:3.4
  script:
    - pip install -r requirements_test.txt
    - pytest --cov trivago -- tests
  tags:
    - docker

test35:
  stage: test
  image: python:3.5
  script:
    - pip install -r requirements_test.txt
    - pytest --cov trivago -- tests
  tags:
    - docker

test36:
  stage: test
  image: python:3.6
  script:
    - pip install -r requirements_test.txt
    - pytest --cov trivago -- tests
  tags:
    - docker
